import Link from 'next/link';
import { Shield } from 'lucide-react';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-zinc-950 text-zinc-300 font-sans p-8 md:p-16">
      <div className="max-w-3xl mx-auto bg-zinc-900 border border-zinc-800 p-8 rounded-xl shadow-2xl">
        
        <div className="flex items-center space-x-3 mb-8 pb-6 border-b border-zinc-800">
          <Shield className="w-8 h-8 text-emerald-400" />
          <h1 className="text-2xl font-bold text-zinc-100">Terms of Service & Disclaimer</h1>
        </div>

        <div className="space-y-6 text-sm leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-zinc-200 mb-2">1. Acceptance of Terms</h2>
            <p>By accessing and using XMLCraft ("the Software"), you accept and agree to be bound by the terms and provisions of this agreement. If you do not agree to abide by these terms, please do not use this service.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-200 mb-2">2. Zero Liability & "AS IS" Provision</h2>
            <p className="text-amber-400 font-medium bg-amber-400/10 p-3 rounded border border-amber-900/50 mb-3">
              THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
            </p>
            <p>XMLCraft performs complex data manipulation, including XML-to-JSON conversions, XPath evaluations, and XSLT transformations. Due to the inherent complexity of enterprise XML standards (such as ISO 20022), data conversions may occasionally result in formatting discrepancies or data loss.</p>
            <p className="mt-2 font-medium">You are strictly responsible for verifying the accuracy of any output generated by XMLCraft before utilizing it in production environments, financial systems, or healthcare databases.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-200 mb-2">3. Data Privacy & Air-Gapped Architecture</h2>
            <p>XMLCraft is designed as a zero-egress client-side tool. All processing occurs within your browser's local memory. We do not transmit, collect, store, or intercept any of the payloads you input into the Software. However, ensuring the security of your physical workstation and browser environment remains entirely your responsibility.</p>
          </section>
        </div>

        <div className="mt-10 pt-6 border-t border-zinc-800 text-center">
          <Link href="/" className="inline-flex items-center space-x-2 text-blue-400 hover:text-blue-300 transition-colors bg-blue-950/30 px-4 py-2 rounded-lg border border-blue-900/50">
            <span>&larr; Return to XMLCraft Workbench</span>
          </Link>
        </div>

      </div>
    </div>
  );
}
